<?php
require_once '../main.inc.php';
$BuildPage = new BuildPage();
$BuildPage->printHeader('Privacy and Tracking Information');

echo('
<h2>TERMS OF USE FOR SITES</h2>
PLEASE READ THESE TERMS OF USE (&quot;TERMS&quot;) CAREFULLY BEFORE ACCESSING OR PARTICIPATING IN ANY CHATROOM, NEWSGROUP, BULLETIN BOARD, MAILING LIST, WEBSITE, TRANSACTION OR OTHER ON-LINE FORUM AVAILABLE AT '.strtoupper(SITE_URL).' OR OTHER AFFILIATED SITES (&quot;SITE&quot; OR &quot;SITES&quot;). BY USING AND PARTICIPATING IN THESE SITES, YOU SIGNIFY THAT YOU HAVE READ THESE TERMS AND AGREE TO BE BOUND BY AND COMPLY WITH THEM. IF YOU DO NOT AGREE TO BE BOUND BY THESE TERMS, PLEASE PROMPTLY EXIT ALL SITES. '.strtoupper(SITE_SHORTNAME).' RESERVES THE RIGHT TO MODIFY THESE TERMS AT ANY TIME WITH OR WITHOUT NOTICE.<br /><br />
<h3>Information We Collect by Automated Means</h3>
When you visit our Sites, we occasionally collect information by automated means, using technologies such as cookies and Web beacons.<br /><br />
Cookies are snippets of code that we send to your computer or other Internet-connected device to uniquely identify your browser or to store information or settings in your browser. This is a common practice across the web. Your browser may notify you or manipulate the way you interact with cookies. Please note, however, that without cookies you may not be able to use all of the features of our Sites.<br /><br />
We may log information such as your device and operating system type, browser type, domain, device ID, and other system settings, as well as the language your system uses and the country and time zone where your device is located. To control which Web servers collect information by automated means, we may place tags on our Web pages called “Web beacons”, which are small files that work much the same way as cookies.<br /><br />
We use third-party Web analytics services on our Sites, such as those of Google Analytics. These service providers use cookies and Web beacons or other technology to help us analyze how users use the Sites. The information collected by such technology (including, where applicable, your IP address) will be disclosed to these service providers, who use the information to facilitate the evaluation of your use of the Sites. You can opt out of most Google Analytics tracking by visiting your Google account settings.<br /><br />
<h3>Permission to Use Materials</h3>
In consideration for your agreement to the terms and conditions contained here, '.SITE_FULLNAME.' grants you a personal, non-exclusive, non-transferable license to access and use the Sites. User may not download material from the content sections of Sites under any conditions (such as copy and paste of page content). User may download material from the sections of Sites only for User&rsquo;s own personal, non-commercial use when the item is intended as a download, such as a form to complete on paper or a document for archive. User may not otherwise copy, reproduce, retransmit, distribute, publish, commercially exploit or otherwise transfer any material. The burden of determining that use of any information, software or any other content on the Site is permissible rests with User.<br />
<h3>Links to Other Sites</h3>
'.SITE_SHORTNAME.'&rsquo;s Site may include hyperlinks to websites maintained or controlled by others. '.SITE_SHORTNAME.' is not responsible for and does not routinely screen, approve, review or endorse the contents of or use of any of the products or services that may be offered at these websites.<br />
<h3>Disclaimer of Warranty/Limitation of Liability</h3>
THESE SITES AND ANY INFORMATION, PRODUCTS OR SERVICES THEREIN ARE PROVIDED &quot;AS IS&quot; WITHOUT WARRANTY OF ANY KIND, EITHER EXPRESS OR IMPLIED, INCLUDING WITHOUT LIMITATION, THE IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR USE OF A PARTICULAR PURPOSE, OR NONINFRINGEMENT. '.SITE_SHORTNAME.' does not warrant, and hereby disclaims any warranties, either express or implied, with respect to the accuracy, adequacy or completeness of any Site, information obtained from a Site, or link to a Site. '.SITE_SHORTNAME.' does not warrant that Sites will operate in an uninterrupted or error-free manner or that Sites are free of viruses or other harmful components. Use of information obtained from or through these Sites is at your own risk.<br /><br />
YOU AGREE THAT '.strtoupper(SITE_SHORTNAME).' WILL NOT BE LIABLE TO YOU FOR ANY LOSS OR DAMAGES, EITHER ACTUAL OR CONSEQUENTIAL, ARISING OUT OF OR RELATING TO THESE TERMS, OR TO YOUR (OR ANY THIRD PARTY&rsquo;S) USE OR INABILITY TO USE A SITE, OR TO YOUR PLACEMENT OF CONTENT ON A SITE, OR TO YOUR RELIANCE UPON INFORMATION OBTAINED FROM OR THROUGH A SITE. IN PARTICULAR, '.strtoupper(SITE_SHORTNAME).' WILL HAVE NO LIABILITY FOR ANY CONSEQUENTIAL, INDIRECT, PUNITIVE, SPECIAL OR INCIDENTAL DAMAGES, WHETHER FORESEEABLE OR UNFORESEEABLE, (INCLUDING, BUT NOT LIMITED TO, CLAIMS FOR DEFAMATION, ERRORS, LOSS OF DATA, OR INTERRUPTION IN AVAILABILITY OF DATA), ARISING OUT OF OR RELATING TO THESE TERMS, YOUR USE OR INABILITY TO USE A SITE, OR ANY PURCHASES ON THIS SITE, OR YOUR PLACEMENT OF CONTENT ON A SITE, OR TO YOUR RELIANCE UPON INFORMATION OBTAINED FROM OR THROUGH A SITE, WHETHER BASED IN CONTRACT, TORT, STATUTORY OR OTHER LAW, EXCEPT ONLY IN THE CASE OF DEATH OR PERSONAL INJURY WHERE AND ONLY TO THE EXTENT THAT APPLICABLE LAW REQUIRES SUCH LIABILITY.<br />
<h3>Trademarks</h3>
The logo, name and all graphics on the Sites of '.SITE_SHORTNAME.' may be trademarks of '.SITE_SHORTNAME.' or its affiliates. Use, reproduction, copying or redistribution of trademarks, without the written permission of the owner or its affiliates is prohibited. All other trademarks or servicemarks appearing on the Site are the marks of their respective owners.<br />
<h3>Your Account</h3>
If you use this site, you are responsible for maintaining the confidentiality of your account and password, if any, and for restricting access to your computer, and you agree to accept responsibility for all activities that occur under your account or password. If you are under 18, you may purchase products or services only through a parent or guardian. You agree that billing and registration information you provide on the Sites will be accurate and complete. '.SITE_SHORTNAME.' and its affiliates reserve the right to refuse service, terminate accounts, remove or edit content, or cancel orders in their sole discretion.<br />
<h3>Copyright Information</h3>
COPYRIGHT &copy; '.date('Y').' '.strtoupper(SITE_FULLNAME).'. <u>ALL RIGHTS RESERVED</u>. DO NOT DUPLICATE IN WHOLE OR PART WITHOUT PERMISSION OF '.strtoupper(SITE_FULLNAME).'.<br /><br />
ALL CONTENT ON '.strtoupper(SITE_SHORTNAME).' SERVERS (INCLUDING SUBDOMAINS OR ROOT DOMAINS) ARE PROPERTY OF '.strtoupper(SITE_FULLNAME).'.


<hr /><span class="textCenter"><a href="../index.php"><input type="button" id="back" value="Home" /></a></span>
');

$BuildPage->printFooterSpecial();
?>